### ISSUE TITLE
Add Ability to Export Results to CSV

### ISSUE THREAD

**Issue by blad** [blad/trendy-cucumber#1]
Results should be written to a file so that they can be imported into excel, sheets, or pages.

**Comment by benwiley4000** [comment]
@blad Please provide an example JSON file for testing - thank you!

**Comment by benwiley4000** [comment]
I found some sample results here: https://www.relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter

It may be useful to link to that or a similar page in the README.
